//! `grans skill`: print an agent skill that points at `--help`.
//!
//! The skill is a snapshot once it is redirected into a file, so it carries
//! nothing that a later grans could contradict: no commands, flags, or
//! examples of its own, only when to reach for grans and where its
//! documentation is. The one thing that cannot move into the help is the
//! frontmatter, which an agent reads from disk to decide whether grans is
//! relevant before anything has prompted it to run a command.

/// The skill, with a placeholder where the version goes.
const TEMPLATE: &str = include_str!("skill.md");

const VERSION_PLACEHOLDER: &str = "{version}";

/// The skill as printed by the grans whose version is `version`.
fn render(version: &str) -> String {
    TEMPLATE.replace(VERSION_PLACEHOLDER, version)
}

/// Print the skill to stdout. Agent tools keep skills in different places,
/// so where it goes is left to the caller's redirect.
pub fn run() {
    print!("{}", render(env!("GRANS_VERSION")));
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::cli::help::check::{mentioned_commands, names_a_command};

    /// The frontmatter fields, between the two `---` lines that open the file.
    fn frontmatter(skill: &str) -> Vec<(&str, &str)> {
        let body = skill
            .strip_prefix("---\n")
            .expect("the skill should open with frontmatter");
        let (fields, _) = body
            .split_once("\n---\n")
            .expect("the frontmatter should be closed");
        fields
            .lines()
            .map(|line| line.split_once(": ").expect("a `key: value` line"))
            .collect()
    }

    #[test]
    fn frontmatter_names_the_skill_and_says_when_to_use_it() {
        let skill = render("2026.8.30");
        let fields = frontmatter(&skill);

        assert_eq!(fields[0], ("name", "grans"));
        let (key, description) = fields[1];
        assert_eq!(key, "description");
        assert!(description.contains("meetings"));
        assert_eq!(fields.len(), 2);
    }

    #[test]
    fn names_the_version_that_generated_it() {
        let skill = render("2026.8.30 (abc1234)");

        assert!(skill.contains("Generated by grans 2026.8.30 (abc1234)."));
        assert!(!skill.contains(VERSION_PLACEHOLDER));
    }

    #[test]
    fn every_command_it_names_is_real() {
        let commands = mentioned_commands(&render("dev"));
        assert!(!commands.is_empty());
        for command in commands {
            names_a_command(&command).unwrap();
        }
    }

    #[test]
    fn documents_no_usage_of_its_own() {
        // Anything more than "ask grans for help" would go stale in a file
        // that outlives the binary that wrote it.
        for command in mentioned_commands(&render("dev")) {
            assert!(
                command == "grans skill" || command.ends_with(" --help"),
                "the skill should only point at --help, but names `{command}`"
            );
        }
    }

    #[test]
    fn ends_with_a_single_newline() {
        let skill = render("dev");
        assert!(skill.ends_with('\n') && !skill.ends_with("\n\n"));
    }
}
